### ISSUE TITLE
Feature Request: It would be great if the scenarios were collapsible

### ISSUE THREAD

**Issue by humphreyn** [damianszczepanik/cucumber-sandwich#14] opened 2015-09-18 21:27 UTC
It would be nice to have a toggle button in the menu to toggle on/off collapsible scenario steps so that you only say the scenario and the steps were hidden / visible by clicking on the button.

Clicking on the scenario to also toggle making the steps visible or not would also be great.

It would make it easier to scroll quickly to the failed scenarios

**Comment by damianszczepanik** [comment] 2016-02-25 20:14
Duplicate of damianszczepanik/cucumber-reporting/issues/130

**Closed by damianszczepanik** 2016-02-25 20:14 UTC

**Comment by humphreyn** [comment] 2016-02-26 09:26
Brilliant, thanks Damian
