### ISSUE TITLE
Feature Request: Wrap into Jenkins for build monitor of cucumber-jvm

### ISSUE THREAD

**Issue by jonathan-waite** [damianszczepanik/cucumber-sandwich#1] opened 2014-01-05 02:01 UTC
It would be great to wrap this into the jenkins cucumber reports so you could see the progress of your CI builds.

**Comment by damianszczepanik** [comment] 2016-02-25 20:19
Duplicate of damianszczepanik/cucumber-reporting/issues/33

**Closed by damianszczepanik** 2016-02-25 20:19 UTC
